# ---
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_feb-13_aks_northeurope
#   name: azure-load-balancer
# spec:
#   loadBalancerIP: 40.69.87.243
#   type: LoadBalancer
#   ports:
#     - port: 5432
#       targetPort: 5432
#       protocol: TCP
#   selector:
#     app: postgres-slova
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-slova
#   namespace: slova
# spec:
#   selector:
#     app: postgres-slova
#   ports:
#     - protocol: TCP
#       port: 5432
#       targetPort: 5432
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-slova-tcp-services
data:
  5432: "slova/postgres-slova:5432"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-slova
  # labels:
  #   app.kubernetes.io/name: ingress-nginx
  #   app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: proxied-tcp-5432
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    # app.kubernetes.io/part-of: ingress-nginx
