apiVersion: v1
kind: Namespace
metadata:
  name: slova
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-slova
  namespace: slova
  labels:
    app: postgres-slova
spec:
  containers:
    - name: postgres
      image: postgres:13.2
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
